require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.barbar'
require 'user.lualine'
require 'user.indentline'
require 'user.nvim-tree'
require 'user.vimwiki'
require 'user.marks'
-- require 'user.netrw'
require 'user.dirvish'
require 'user.lsp'
require 'user.treesitter'
require 'user.cmp'
require 'user.emmet'
-- require 'user.fzf'
require 'user.telescope'
require 'user.gitsigns'
-- require 'user.gitgutter'
-- require 'user.neoformat'
require 'user.autocommands'
require 'user.abbreviation'
require 'user.which-key'
require 'user.colorizer'

